import pandas as pd
import requests
from bs4 import BeautifulSoup
import sqlite3
import time

# 1. Load the CSV generated by scraper.py
csv_file = "atlanta_cre_news.csv"
df_urls = pd.read_csv(csv_file)

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}

# 2. Connect to SQLite database (creates database file automatically)
conn = sqlite3.connect("rein_credit_risk.db")
cursor = conn.cursor()

# Create table schema
cursor.execute("""
    CREATE TABLE IF NOT EXISTS article_intelligence (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT,
        url TEXT UNIQUE,
        body_text TEXT,
        scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
""")
conn.commit()

print(f"Beginning full-text extraction for {len(df_urls)} articles...\n")

scraped_count = 0

for index, row in df_urls.iterrows():
    title = row["title"]
    url = row["link"]
    
    try:
        response = requests.get(url, headers=headers, timeout=10)
        
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, "html.parser")
            
            # Target all article body paragraphs
            paragraphs = soup.find_all("p")
            
            # Combine paragraphs into a single cohesive text block
            body_text = " ".join([p.text.strip() for p in paragraphs if len(p.text.strip()) > 30])
            
            if body_text:
                # Save into SQLite database
                cursor.execute("""
                    INSERT OR IGNORE INTO article_intelligence (title, url, body_text)
                    VALUES (?, ?, ?)
                """, (title, url, body_text))
                
                conn.commit()
                scraped_count += 1
                print(f"[{scraped_count}/{len(df_urls)}] Saved: {title[:50]}...")
            
        # Respectful pause to avoid getting rate-limited
        time.sleep(1)
        
    except Exception as e:
        print(f"Error fetching {url}: {e}")

conn.close()
print(f"\nExtraction Complete! {scraped_count} full article bodies saved to 'rein_credit_risk.db'.")